name: ishaqkhan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  get: 4.6.5
  intl: ^0.18.1
  velocity_x: ^4.1.0
  


dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
  uses-material-design: true

